### PR TITLE
Fix facet filters on mobile. Add overlay to HeaderDrawer.

### LINKED ISSUE #1346: Filter drawer Unable to select filters via mobile view or collapsed desktop setting on collections page
**Describe the current behavior**

When trying to select filters via mobile view or collapsed desktop on collection pages, the drawer closes prematurely:

[](https://screenshot.click/bv7k8-v0kfi-0to4r-artet-8mzlm.gif)

It doesn't happen on touch devices though.

**Describe the expected behavior**

Users should be able to select filters via mobile or collapsed desktop without the drawer closing prematurely:

[](https://screenshot.click/kowb8-yoauw-1ko8a-tgzu0-2rh0v.gif)

**More information**

 - Changes were made via the following PR: [#1242](https://github.com/Shopify/dawn/pull/1242) to fix issue: [#1188](https://github.com/Shopify/dawn/issues/1188)
 - I believe the fix was implemented to ensure that when `closeMenuDrawer()` was called with no params, the menu drawer would close: “Allow clicking outside menu to close menu, Ensure closing submenu does not also close main menu”.
 - Unfortunately it seems that now when you try to click on some elements (including input elements) within the drawer menu of the **Facets** filter and sort feature, the `closeMenuDrawer()` is called and closes the menu, rendering users unable to use the filtering feature correctly.

**Device information (browsers and operating system)**
- Chrome Version 97.0.4692.99
- macOS Version 12.2
- Themes: Dawn 3.0.0

**Possible solution**

 - As a possible solution, see changes made to `closeMenuDrawer` function [via the following commit.](https://github.com/Shopify/dawn/commit/7f73c1ce5574226345204377ebff978cbb153f32)
 - Adding back the if statement `if (event !== undefined)` appears to fix this issue, but may result in reviving the issues found in [#1188](https://github.com/Shopify/dawn/issues/1188)

```diff
  closeMenuDrawer(event, elementToFocus = false) {
-    if (event !== undefined) {
      this.mainDetailsToggle.classList.remove('menu-opening');
      this.mainDetailsToggle.querySelectorAll('details').forEach(details =>  {
        details.removeAttribute('open');
        details.classList.remove('menu-opening');
      });
      document.body.classList.remove(`overflow-hidden-${this.dataset.breakpoint}`);
      removeTrapFocus(elementToFocus);
      this.closeAnimation(this.mainDetailsToggle);
-    }
  }
```

### PR DESCRIPTION
**Pull request by LucasLacerdaUX**
**Why are these changes introduced?**

Fixes #1346 and adds an overlay to Header, like suggested by @melissaperreault in #1242.

**What approach did you take?**
- Revert the change made in #1242 by adding back the check if `event === undefined`.
- Added an overlay to Header navigation on mobile. This overlay prevents accidental navigation when the user taps to exit the drawer, but ends up clicking a link.

**Testing steps/scenarios**
- [ ] Test Facet Filters on **mobile**, **desktop (mouse)**, and **desktop (mouse) with mobile viewport size**.
    - [ ] Click outside the drawer to close it.
    - [ ] Check if navigating categories and toggling filters works with no unexpected closing.
- [ ] Test Navigation Menus on **mobile**, **desktop (mouse)**, and **desktop (mouse) with mobile viewport size**.
    - [ ] Click outside the drawer to close it.
    - [ ] Check if navigating menus and submenus still work with no unexpected closing.

**Demo links**
_Please include a link to a demo store that includes preconfigured sections and settings to allow reviewers to easily test the features you are working on._

- [Store](https://os2-demo.myshopify.com/?preview_theme_id=127583780886)
- [Editor](https://os2-demo.myshopify.com/admin/themes/127583780886/editor)

**Checklist**
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

File: assets/global.js [hunk 1]
```diff
@@ -343,6 +343,8 @@ class MenuDrawer extends HTMLElement {
   }
 
   closeMenuDrawer(event, elementToFocus = false) {
+    if (event === undefined) return;
```
Comment (KaichenWang) [inline assets/global.js:346]: This fixes the issue, but the root cause is in the function below. When a filter is selected, the focus shifts out of the drawer which causes `onFocusOut()` to trigger. By adding this condition to`closeMenuDrawer()`, `onFocusOut()` will now never actually close the dialog, since no event is passed as param.
``` js
onFocusOut(event) {
  setTimeout(() => {
    if (this.mainDetailsToggle.hasAttribute('open') && !this.mainDetailsToggle.contains(document.activeElement)) this.closeMenuDrawer();
  });
}
  ```

**Review by KaichenWang — APPROVED** [review]
Looks good! 

Since this fixes a `sev 1` issue, I'm ok with merging asap, but left a comment regarding the root cause, which we can investigate at a later time.

**Review by ludoboludo — APPROVED** [review]
Tested on android, chrome and safari and looks good 👍  🚢
