### PR TITLE
Product A11Y: Fix invalid HTML and announce price when updating variants

### LINKED ISSUE #126: [Product] Invalid HTML markup
## Issue summary

1. The `id` values for each Product variant `input` features invalid, space separated values: `id` can only have a single value.
2. `select` features invalid `form` value.
3. Boolean attribute `disabled` features invalid value.

Invalid markup could cause issues for screen readers and other systems such as search engines which parse HTML content.

#### HTML

```html
<input
  type="radio"
  id="template--14172034990102__main-Size <p>-0"
  name="Size <p>"
  value="35"
  form="product-form-template--14172034990102__main"
  checked=""
/>
<label for="template--14172034990102__main-Size <p>-0">35</label>

<!-- … -->

<select
  name="id"
  id="Variants-template--14172034990102__main"
  class="select__select"
  form="product-form"
>
  <!-- … -->
</select>

<!-- … -->

<button
  type="button"
  class="slider-button slider-button--prev"
  name="previous"
  aria-label="Slide left"
  disabled="true"
>
  <!-- … -->
</button>
```

## Steps to reproduce

1. Go to a Dawn Product page with a variant options with any supported browser.
2. Use [NU Html Validator](https://validator.w3.org/nu/#textarea) to validate the HTML markup.

### Expected

- Valid HTML to be in use.

### Actual

- Invalid HTML is present.

## Recommendation

1. Adjust the generated `id` values to be one single value.
2. Adjust the `select` element `form` attribute to match the `id` of the parent `form`.
3. Remove the value from the `disabled` attribute.

#### HTML

```html
<input
  type="radio"
  id="template--14172034990102__main-Size-0"
  name="Size <p>"
  value="35"
  form="product-form-template--14172034990102__main"
  checked=""
/>
<label for="template--14172034990102__main-Size-0">35</label>

<!-- … -->

<select
  name="id"
  id="Variants-template--14172034990102__main"
  class="select__select"
  form="product-form-template--14172034990102__main"
>
  <!-- … -->
</select>

<!-- … -->

<button
  type="button"
  class="slider-button slider-button--prev"
  name="previous"
  aria-label="Slide left"
  disabled
>
  <!-- … -->
</button>
```

<!-- #### Diff

```diff

``` -->

## Specifications

- **Component:** Product
- **WCAG Principal:** Robust
- **WCAG SC:** [4.1.1 Parsing](https://www.w3.org/WAI/WCAG21/Understanding/parsing.html)
- **Severity:** Low
- **Effort:** Low

### LINKED ISSUE #463: [Product] Change of status on variant selection not announced
## Issue summary

On product pages and featured product section, the status of the product may change as the user selects a variant. For example, selection one size or another reveals if the product is on sale or sold out. This status is only conveyed visually. Screen reader users may miss this update which could lead to a confusing or frustrating user experience (as described in https://github.com/Shopify/dawn/issues/1.)

<details>
  <summary>Screenshots</summary>

Gif of product page. Size variant selector moves between and selects shirt sizes. Sale price and sold out status text is updated above the selectors.

</details>

#### HTML

```html
<div
  class="no-js-hidden"
  id="price-template--15004892561579__1629739262600943ca"
  …
>
  <div class="price price--large price--on-sale">
    <!-- Price content… -->
    <span class="badge price__badge-sale color-accent-2" aria-hidden="true">
      Sale
    </span>
    <span class="badge price__badge-sold-out color-inverse" aria-hidden="true">
      Sold out
    </span>
  </div>
</div>
```

## Steps to reproduce

1. Go to a Dawn store, Product page with any supported browser
2. With an active screen reader, navigate to the variant selector and activate variants via arrow keys to reveal status content

### Expected

- Price and status content to be announced by the screen reader.

### Actual

- Price and status is not announced.

### HTML structure…

1. Add the `role` attribute to the `div#price-template` content container, setting its value to `status`. This will create a live region for screen readers to announce changed content.
2. Remove the `aria-hidden` attributes from the `span.badge` elements in order for screen readers to include this information.

#### HTML

```html
<div
  class="no-js-hidden"
  id="price-template--15004892561579__1629739262600943ca"
  …
  role="status"
>
  <div class="price price--large price--on-sale">
    <!-- Price content… -->
    <span class="badge price__badge-sale color-accent-2">
      Sale
    </span>
    <span class="badge price__badge-sold-out color-inverse">
      Sold out
    </span>
  </div>
</div>
```

<!-- #### Diff

```diff
- line removed
+ line added
``` -->

## Specifications

- **WCAG Principal:** Robust
- **WCAG SC:** [4.1.3 Status Messages](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html)
- **Severity:** High
- **Effort:** Low

### PR DESCRIPTION
**Pull request by LucasLacerdaUX**
**Why are these changes introduced?**
Accessibility fixes for Product page and Featured Product sections:
- Fix invalid HTML markup
- Add `role="status"` to price container so the price is announced when variants are updated

Fixes #126 
Fixes #463

**What approach did you take?**
Followed suggestions on the issues.

To fix invalid HTML:
- Replaced `option.name` with `option.position` on the radio button `id`s. `option.name` can have spaces, resulting in a space separated (invalid) `id` attribute.
- Updated all `form` attributes to use the same `{{ product_form_id }}` to keep consistency.
- Updated `disabled="true"` (invalid) to `disabled="disabled"` (valid) in all JS files that are using this property

To announce price variants:
- Removed `aria-hidden` from badges in `price.liquid`.
- Added `role="status"` to the price region.

**Demo links**
- [Store](https://os2-demo.myshopify.com/?preview_theme_id=126539268118)
- [Editor](https://os2-demo.myshopify.com/admin/themes/126539268118/editor)

**Suggested Tests**
Accessibility
- [ ] Use a Screen Reader to test if prices are announced when the variant price or availability changes. [Suggested product](https://os2-demo.myshopify.com/products/brick-apple).

Functionality
- [ ] Check if Product form still works as expected in products with multiple variants on the product page and featured product section.

**Checklist**
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

File: assets/global.js [hunk 1]
```diff
@@ -527,13 +527,13 @@ class SliderComponent extends HTMLElement {
     this.currentPage = Math.round(this.slider.scrollLeft / this.sliderLastItem.clientWidth) + 1;
 
     if (this.currentPage === 1) {
-      this.prevButton.setAttribute('disabled', true);
+      this.prevButton.setAttribute('disabled', 'disabled');
```
Comment (LucasLacerdaUX) [inline assets/global.js:530]: Any suggestions on what to use here? 

I opted for `'disabled'` as it seems to be valid and more explicit than an empty string `''`, which I believe can be confusing for quickly glancing at the code, but I'm open to suggestions :)

Comment (ludoboludo) [reply assets/global.js:530]: Yeah it doesn't seem like we can add an attribute without a value. With `disabled` as the value it seems good 👍

**Review by ludoboludo — APPROVED** [review]
LGTM 🚀

**Review by kmeleta — APPROVED** [review]
Code looks good. Tested in VO 👍
