### PR TITLE
Fix old results shown on predictive search

### LINKED ISSUE #2199: [Predictive search] Old results are shown when the query is cleared and rewriten
## Describe the current behavior

1. Write some query on the search input (With predictive search activated)
2. Remove the input, with the clear button or with backspace. The results are hidden.
3. Start writing another word: the old results appear.

## Describe the expected behavior

Current behaviour that shouldn't be changed:
- When I add new characters to the current query, the old results are shown since they might still be relevant

Ideal behaviour:
- When I change the query (remove some characters and write new different ones) the old results are not shown since they are no longer relevant

Compromise solution if the ideal behaviour is not possible:
- When I clear the query (manually or with the clear button) and then start writing again, the old results should not be shown.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 7.0.1
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Additional context/screenshots

[Video showing the bug](https://screenshot.click/05-59-sfyuo-dx0mx.mp4)

### PR DESCRIPTION
**Pull request by FCalabria**
### PR Summary: 

Hide stale results on the predictive search when writting a new query and refresh the "search for" button with the new term as soon as possible.

### Why are these changes introduced?

Fixes #2199 and improves the user experience updating the "search for" button while the user types, instead of waiting for the predictive search query to resolve.

### What approach did you take?

To fix the bug, delete the results and show the loading spinner when the new query is not an addition over the old one.

For the improvement, I used a search and replace technique modifying the html on the fly with JS. I could not figure out a way to identify the search term that wasn't just looking for the string itself (depending on the language the quote symbol and the term position changes). This can cause a problem when the user looks for exactly the label on the search button ("Search for...") which i avoided not replacing anything if there is more than one match.

### Testing steps/scenarios

- [ ] When writing a query, the search term in the button updates before the predictive search results
- [ ] When a query is total or partially deleted and then a different term is written, the old predictive search results are not shown, just a loading state.

### Demo links

- [Store](https://afpsbbuvix8y3fsp-45840990230.shopifypreview.com?preview_theme_id)
- [Editor](https://os2-demo.myshopify.com/admin/themes/139285364758/editor)

### Checklist
- [x] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [x] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

### CODE REVIEW

File: assets/predictive-search.js [hunk 1]
```diff
@@ -263,6 +289,10 @@ class PredictiveSearch extends SearchForm {
     this.resultsMaxHeight = false
     this.predictiveSearchResults.removeAttribute('style');
   }
+
+  clearResources() {
```
Comment (NathanPJF) [inline assets/predictive-search.js:293]: Can you use the existing `closeResults` method for this instead? Is this additional method necessary?

File: sections/predictive-search.liquid [hunk 2]
```diff
@@ -7,7 +7,7 @@
 %}
   <div id="predictive-search-results" role="listbox">
     {%- if first_column_results_size > 0 or predictive_search.resources.products.size > 0 -%}
-      <div class="predictive-search__results-groups-wrapper{% unless predictive_search.resources.products.size > 0 %} predictive-search__results-groups-wrapper--no-products{% endunless %}{% unless predictive_search.resources.queries.size > 0 or predictive_search.resources.collections.size > 0 %} predictive-search__results-groups-wrapper--no-suggestions{% endunless %}">
+      <div id="predictive-search__results-groups-wrapper" class="predictive-search__results-groups-wrapper{% unless predictive_search.resources.products.size > 0 %} predictive-search__results-groups-wrapper--no-products{% endunless %}{% unless predictive_search.resources.queries.size > 0 or predictive_search.resources.collections.size > 0 %} predictive-search__results-groups-wrapper--no-suggestions{% endunless %}">
```
Comment (ludoboludo) [inline sections/predictive-search.liquid:10]: I can see why you'd have the `__` underscores there. But since we didn't use that same pattern for `predictive-search-option-search-keywords` I think we should approach it the same way. With a `-` instead.

**Review by ludoboludo — COMMENTED** [review]
Looking good. Ill test a bit tomorrow some scenarios. 
But no bugs/issue noticed 👍

File: assets/predictive-search.js [hunk 3]
```diff
@@ -99,6 +108,23 @@ class PredictiveSearch extends SearchForm {
...
   }
 
+  updateSearchForTerm(previousTerm, newTerm) {
+    const searchForButton = this.querySelector("#search-for-button");
+    const currentButtonText = searchForButton?.innerText;
+    if (currentButtonText) {
+      const buttonIcon = searchForButton.innerHTML.replace(
+        currentButtonText,
+        ""
+      );
```
[the remark this answers is not in the document]
Comment (ludoboludo) [reply assets/predictive-search.js:118]: I think I'd suggest more grabbing the icon via it's class or element name 🤔 `searchForButton.querySelector('svg')`
It would be easier to read.

File: assets/predictive-search.js [hunk 4]
```diff
@@ -27,7 +27,16 @@ class PredictiveSearch extends SearchForm {
 
   onChange() {
     super.onChange();
-    this.searchTerm = this.getQuery();
+    const newSearchTerm = this.getQuery();
+    if (!this.searchTerm || !newSearchTerm.startsWith(this.searchTerm)) {
+      // Hide the results when they are no longer relevant for the new search term
+      this.closeResults(false);
```
Comment (ludoboludo) [inline assets/predictive-search.js:33]: This does what the function you had before did 🤔 
Here are two video comparisons: [using clearResources()](https://screenshot.click/26-37-z1bah-zoj8s.mp4) & [using closeResults(false)](https://screenshot.click/26-41-laoke-eu6yn.mp4)

Comment (FCalabria) [reply assets/predictive-search.js:33]: I tested and it seemed to be fine, but maybe my internet was too fast to appreciate the difference. Thanks for the thorough testing!

File: sections/predictive-search.liquid [hunk 5]
```diff
@@ -7,7 +7,7 @@
 %}
   <div id="predictive-search-results" role="listbox">
     {%- if first_column_results_size > 0 or predictive_search.resources.products.size > 0 -%}
-      <div class="predictive-search__results-groups-wrapper{% unless predictive_search.resources.products.size > 0 %} predictive-search__results-groups-wrapper--no-products{% endunless %}{% unless predictive_search.resources.queries.size > 0 or predictive_search.resources.collections.size > 0 %} predictive-search__results-groups-wrapper--no-suggestions{% endunless %}">
+      <div id="predictive-search-results-groups-wrapper"class="predictive-search__results-groups-wrapper{% unless predictive_search.resources.products.size > 0 %} predictive-search__results-groups-wrapper--no-products{% endunless %}{% unless predictive_search.resources.queries.size > 0 or predictive_search.resources.collections.size > 0 %} predictive-search__results-groups-wrapper--no-suggestions{% endunless %}">
```
Comment (ludoboludo) [inline sections/predictive-search.liquid:10]:
```suggestion
      <div id="predictive-search-results-groups-wrapper" class="predictive-search__results-groups-wrapper{% unless predictive_search.resources.products.size > 0 %} predictive-search__results-groups-wrapper--no-products{% endunless %}{% unless predictive_search.resources.queries.size > 0 or predictive_search.resources.collections.size > 0 %} predictive-search__results-groups-wrapper--no-suggestions{% endunless %}">
```

**Review by NathanPJF — APPROVED** [review]
Thanks for owning this @FCalabria 

It doesn't seem like the failing theme check step will be a blocker to merge. I see that the recent PRs have merged without this passing ([example](https://github.com/Shopify/dawn/pull/2253#event-8347446695)). But don't forget to rebase this first 🔂 🚢

**Comment by FCalabria** [comment]
> I think it's looking good 👍 I can see how the proposed change by Nathan would make sense too 👍 About wrapping the text in a span. Not sure if we need the data attribute since we can select the `span` element itself.

I decided to use the data attribute because with the span i don't need the reference to the full button anymore, so i could delete that id.

> It doesn't seem like the failing theme check step will be a blocker to merge. I see that the recent PRs have merged without this passing (https://github.com/Shopify/dawn/pull/2253#event-8347446695). But don't forget to rebase this first 🔂 🚢

Sure! I was waiting for you to finish reviewing to not mess up anything

**Review by NathanPJF — APPROVED** [review]
🎩 I just re-tophatted https://os2-demo.myshopify.com/?preview_theme_id=139285364758

**Review by ludoboludo — APPROVED** [review]
🎉
